### PR TITLE
Updated certificate from https://github.com/AuthorizeNet/sdk-php/blob…

### PR DESCRIPTION
**Pull request by ghost**
https://community.developer.authorize.net/t5/The-Authorize-Net-Developer-Blog/Authorize-Net-Begins-Infrastructure-and-SHA-2-Certificate/ba-p/49615

### CODE REVIEW

**Comment by ajbdev** [comment]
Verified against https://raw.githubusercontent.com/AuthorizeNet/sdk-php/master/lib/ssl/cert.pem

**Comment by ajbdev** [comment]
FYI, I am marking this package as abandoned on packagist.org in favor of authorize.net's PHP SDK that now supports composer properly.

**Comment by prplaaron** [comment]
Yeah, no worries. We've got some old dependencies we should update that still use this. Could you also tag this? I'm trying to satisfy https://packagist.org/packages/payum/payum#0.9.0 which uses ajbdev/authorizenet-php-api: 1.1.*

**Comment by ajbdev** [comment]
Tagged 1.1.81

**Pull request merged**
